### ISSUE TITLE
NullReferenceException during Performed callback - Stand Alone Windows

### ISSUE THREAD

**Issue by NicoFrois** [keijiro/VfxMinisExamples#1]
First I want to thank you for your awesome work! Your proyects are really fun to play with!

I think this error could be because of the preview state of the new Input System, but I'm posting it here in case it's related

In the stand alone version of my proyect (also tested with the stand alone version of VFXMinisExample) I get this error : NullReferenceException thrown during execution of 'Performed' callback on action 'Action[/MidiDevice/note077,/MidiDevice1/note077]'

Any help is welcome

Here's the log

> NullReferenceException thrown during execution of 'Performed' callback on action 'Action[/MidiDevice/note077,/MidiDevice1/note077]'
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.InputSystem.InputActionState:CallActionListeners(Int32, InputActionMap, InputActionPhase, InlinedArray`1&) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\Actions\InputActionState.cs:1613)
UnityEngine.InputSystem.InputActionState:ChangePhaseOfAction(InputActionPhase, TriggerState&, InputActionPhase) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\Actions\InputActionState.cs:1538)
UnityEngine.InputSystem.InputActionState:ProcessDefaultInteraction(TriggerState&, Int32) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\Actions\InputActionState.cs:1221)
UnityEngine.InputSystem.InputActionState:ProcessControlStateChange(Int32, Int32, Int32, Double, InputEventPtr) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\Actions\InputActionState.cs:898)
UnityEngine.InputSystem.InputActionState:UnityEngine.InputSystem.LowLevel.IInputStateChangeMonitor.NotifyControlStateChanged(InputControl, Double, InputEventPtr, Int64) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\Actions\InputActionState.cs:779)
UnityEngine.InputSystem.InputManager:FireStateChangeNotifications(Int32, Double, InputEvent*) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\InputManager.cs:2769)
UnityEngine.InputSystem.InputManager:UpdateState(InputDevice, InputUpdateType, Void*, UInt32, UInt32, Double, InputEventPtr) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\InputManager.cs:2956)
UnityEngine.InputSystem.InputManager:UpdateState(InputDevice, InputEvent*, InputUpdateType) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\InputManager.cs:2872)
UnityEngine.InputSystem.InputManager:OnUpdate(InputUpdateType, InputEventBuffer&) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\InputManager.cs:2563)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*) (at C:\Users\nicolas.frois\Documents\UnityProjects\VJBand_v3\Library\PackageCache\com.unity.inputsystem@1.0.0-preview.3\InputSystem\NativeInputRuntime.cs:64)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)
(Filename: C:/Users/nicolas.frois/Documents/UnityProjects/VJBand_v3/Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Actions/InputActionState.cs Line: 1613)

**Comment by keijiro** [comment]
Thanks for the report. Unfortunately, this issue doesn't reproduce on my side.

I'm closing this issue now. If it still reproduces on your side, please reopen this ticket and consider sharing a minimum project that can reproduce the issue.
