### ISSUE TITLE
Black canvas

### ISSUE THREAD

**Issue by jvolker** [keijiro/VfxMinisExamples#2]
I'm using the following configuration:

- KORG Nanokontrol 2
- macOS 12.1 (Silicon)
- Unity Editor 2020.3.26f1

When I open the `Animator` scene, press play, then hit buttons and rotate knobs on the midi controller the canvas stays black. Is there anything else that needs to be set up?

**Comment by keijiro** [comment]
If I remember correctly, `Animator` reacts to MIDI note input, so you can't try it with nanoKONTROL.

(I could be wrong, as I haven't touched this repository over a year.)

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
